version: '3'

services:
  app:
    container_name: tit-africa-frontend
    image: tit-africa-frontend
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - 80:80
