name: Deployment Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build & Deploy Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variables
        id: vars
        run: |
          echo "##[set-output name=commit;]$(echo $GITHUB_SHA | head -c7)"

      - name: Log In to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sjiaire
          password: jJIZP534sOgb

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: sjiaire/tit-africa:frontend-${{ steps.vars.outputs.commit }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # - name: Deploy Image
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: http://144.126.157.125:9000/api/webhooks/48e1c88b-5a07-4993-9073-200d588d60ce?tag=frontend-${{ steps.vars.outputs.commit }}
      #     method: POST
